### ISSUE TITLE
Callback should be inside processImages then

### ISSUE THREAD

**Issue by wizardnet972** [theGC/html-webpack-inline-svg-plugin#11]
Hi, @theGC :)

One more thing if you can change in your plugin.

Please move (callback function)[https://github.com/theGC/html-webpack-inline-svg-plugin/blob/master/index.js#L181] inside (then function)[https://github.com/theGC/html-webpack-inline-svg-plugin/blob/master/index.js#L171].

Why?
Because you change the (html) file. but before you store the html content into array. so until your plugin do its thing the html may be change.
so the content in the array is not correct.
I dont think `runPreEmit` will give the answer because it's not obvious that this is the case to use it.

Thanks!

**Comment by theGC** [comment]
would need to set a Promise.all to get this working as `this.files` can contain multiple templates. Will have a quick look

**Comment by wizardnet972** [comment]
correct. :)

**Comment by theGC** [comment]
v1.2.3 now uses Promise.all to ensure the return value is passed when all file updates are complete
