### ISSUE TITLE
Reading generated svgs in-memory from dist instead of src

### ISSUE THREAD

**Issue by fnlctrl** [theGC/html-webpack-inline-svg-plugin#13]
Hi, thanks for this awesome plugin!
I'm using [svg-sprite-loader](https://github.com/kisenka/svg-sprite-loader)'s extract mode that generates a `sprite.svg` to dist, which can be accessed at `dist/sprite.svg`. 

It works well for production builds. However, when developing using `webpack-dev-server` the `sprite.svg` isn't written to disk, so `<img inline src="./sprite.svg"/>` produces the following error: 
```
{ Error: ENOENT: no such file or directory, open 'F:\app\dist\sprite.svg'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'F:\\app\\dist\\sprite.svg' }
```

I'm not sure if there's any config I missed, if not, could this plugin also support reading in-memory files? Thanks!

**Comment by theGC** [comment]
Hey, yeah this is a situation we haven't hit yet. I don't see why we couldn't support this, I'd need to look into how you read these files though as never done it before.

**Comment by fnlctrl** [comment]
I was digging into svg-sprite-loader's source to find out how it creates the svg files. I found that interestingly it already injects variables to `html-webpack-plugin` since this commit half a year ago: https://github.com/kisenka/svg-sprite-loader/commit/8a2d63e49103c0aa39d2c4269d42fd8f089900ba , which can be directly used to inject svg into html output, but this was never documented....
I've tested it and it worked, so I guesss my use case here is solved. Thanks and keep up the good work!

**Comment by theGC** [comment]
Awesome, thanks for posting back. That added `sprites` param seems a pretty solid way of doing this, I'll add something to the readme for others.

**Comment by theGC** [comment]
@fnlctrl would you mind posting a sample of how others could use that param to access their SVGs?

**Comment by fnlctrl** [comment]
Sure. The example can be found at: https://github.com/kisenka/svg-sprite-loader/commit/8a2d63e49103c0aa39d2c4269d42fd8f089900ba#diff-fd88627cc135d43bf60b94c58725d696
```html
<body>
  <% if (htmlWebpackPlugin.files.sprites) { %>
    <% for (var spriteFileName in htmlWebpackPlugin.files.sprites) { %>
      <%= htmlWebpackPlugin.files.sprites[spriteFileName] %>
    <% } %>
  <% } %>
</body>
```

I only have one 'sprite.svg' so it's simply 
```html
<body>
    <%= htmlWebpackPlugin.files.sprites['sprite.svg'] %>
</body>
```

**Comment by theGC** [comment]
so I assume your **img** tag looks something like:

```html
<img inline src="<%= htmlWebpackPlugin.files.sprites['sprite.svg'] %>">
```
Is that about right?

**Comment by theGC** [comment]
sorry - just reread your earlier comment, you don't need this plugin for your use case do you? :)

**Comment by fnlctrl** [comment]
Yeah... since `htmlWebpackPlugin.files.sprites['sprite.svg']` is already a full svg string we don't actually need to inline it  :joy:
