### ISSUE TITLE
keeping the class assigned

### ISSUE THREAD

**Issue by ronjb04** [theGC/html-webpack-inline-svg-plugin#15]
`<img class="logo-svg" inline src="~img/logo.svg" alt="brand logo">`

Is there a way i can keep the class? so i don't have to re-adjust the css i have set for each svg asset again.

Since my logo and all other svg assets was controlled via its class by css.. however after inlining the svg, the class disappeared and all my svg assets in the website has wrong size or no size at all.

thanks in advance

**Comment by zmrhaljiri** [comment]
PR for this feature here: https://github.com/theGC/html-webpack-inline-svg-plugin/pull/21, please, take a look.

**Comment by theGC** [comment]
Just updating the version to 1.3.0. Should be live shortly.
