### ISSUE TITLE
Plugin could not be registered at 'html-webpack-plugin-after-html-processing'. Hook was not found.

### ISSUE THREAD

**Issue by raygerrard** [theGC/html-webpack-inline-svg-plugin#20]
I have tried adding this plugin via @angular-builders/custom-webpack:browser but receive the following error:

Plugin could not be registered at 'html-webpack-plugin-after-html-processing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
Error: Plugin could not be registered at 'html-webpack-plugin-after-html-processing'. Hook was not found.

**Comment by DaSchTour** [comment]
Change the order of Plugins ;)

**Comment by slavafomin** [comment]
Yep, this plugin will not work if initialized before the `HtmlWebpackPlugin`. However, I would suggest to add a more meaningful error message if possible.

**Comment by jonvanputten** [comment]
Hey there,

Also having the problem from above, even with the right order. Am I still doing something wrong?

```
const Path = require('path');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const HtmlWebpackInlineSVGPlugin = require('html-webpack-inline-svg-plugin');

module.exports = {
  entry: {
    app: Path.resolve(__dirname, '../src/scripts/index.js')
  },
  output: {
    path: Path.join(__dirname, '../build'),
    filename: 'js/[name].js'
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
      name: false
    }
  },
  resolve: {
    alias: {
      '~': Path.resolve(__dirname, '../src')
    }
  },
  module: {
    rules: [
      {
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto'
      },
      {
        test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2)(\?.*)?$/,
        use: {
          loader: 'file-loader',
          options: {
            name: '[path][name].[ext]'
          }
        }
      }
    ]
  },
  plugins: [
    new CleanWebpackPlugin(),
    new CopyWebpackPlugin([
      { from: Path.resolve(__dirname, '../public'), to: 'public' }
    ]),
    new HtmlWebpackPlugin({
      template: Path.resolve(__dirname, '../src/index.html')
    }),
    new HtmlWebpackInlineSVGPlugin()
  ]
};
```

**Comment by DRogueRonin** [comment]
Same for me. I got my plugins ordered like this:

```
plugins: [
    new ExtractTextPlugin({
      filename: '[name].css',
    }),

    // HtmlWebpackPlugin
    new HtmlWebpackPlugin({
      template: './src/index.ejs',
      inject: false,
      minify: isProduction,

      // HtmlWebpackInlineSVGPlugin
      svgoConfig: {
        removeTitle: false,
        removeViewBox: true,
      },
    }),
    new HtmlWebpackInlineSVGPlugin({
      runPreEmit: true,
    }),
  ],
```

**Comment by holger-ubivent** [comment]
Which HtmlWebpackPlugin Version was used? I was having the same issue with HtmlWebpackPlugin Version 4.0.0-beta.11, with the Version 3.2.0 it works.

**Comment by zmrhaljiri** [comment]
It would be awesome if the support with HtmlWebpackPlugin version 4+ could be the thing. I'd like to use the HtmlWebpackInlineSvgPlugin in Storybook which uses also version 4 of HtmlWebpackPlugin and so it's failing with the same error.

+1 for the fix, please <3

**Comment by theGC** [comment]
Am I right in thinking HtmlWebpackPlugin v4 is still in development? If so we can push a PR to a separate branch for users who need it. Unfortunately, I'm a bit stuck for time at the moment so won't be able to look at it myself. 

If someone is able to roll a PR I'll push it to a v2 branch so we can maintain support for HtmlWebpackPlugin v3 in v1 ...

**Comment by leosin** [comment]
Error: Plugin could not be registered at 'html-webpack-plugin-after-html-processing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.

**Comment by theGC** [comment]
sorted with v2.x.x
