### ISSUE TITLE
Does not work with `html-webpack-plugin` 4.0.1

### ISSUE THREAD

**Issue by in-in** [theGC/html-webpack-inline-svg-plugin#23]
> Content not from webpack is served from /path/to/project/
(node:21898) UnhandledPromiseRejectionWarning: Error: Plugin could not be registered at 'html-webpack-plugin-after-emit'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.

```js
"html-webpack-inline-svg-plugin": "1.3.0",
"html-webpack-plugin": "4.0.1",
"webpack": "4.42.1",
```

**Comment by mauriciabad** [comment]
I have the same issue.

I just installed the plugin, add the requirement line and add it to the plugins array.

**Comment by leosin** [comment]
+1

**Comment by in-in** [comment]
@leosin Please stop doing this +1 crap! There's no information in your message. 

If you have the same problem, add :+1:  emoji. This action is much better. This allows maintainers to sort issues by the highest priority, and also prevents meaningless messages.
![201161587766302](https://user-images.githubusercontent.com/8797432/80261533-586bdd80-8693-11ea-971c-7688b28881a9.png)

**Comment by theGC** [comment]
sorted with v2.x.x
