### ISSUE TITLE
Load in dev mode the generated svg sprite from network instead from filesystem

### ISSUE THREAD

**Issue by davidpelayo** [theGC/html-webpack-inline-svg-plugin#28]
I'm running into the following issue, when building for development:

- Building my svg sprite using https://github.com/Epimodev/svg-sprite-html-webpack
- Needing to inline the generated svg sprite into my extracted html document of my single page application.

However, this plugin does not allow me to do such process because [it's directly expecting to have the file already created within the file system](https://github.com/theGC/html-webpack-inline-svg-plugin/blob/master/index.js#L468). My request here would be to allow the consumer to configure the plugin in such a way that it would operate to load the svg file from network too.

So, if the configuration says nothing, it operates the same.
If the configuration says to load the files from network, use the dev-server host to catch the svg content via HTTP request at build time.

Does this make sense or am I missing something?

AFAIK the webpack-dev-server is not writing its ouput to the filesystem, so the only alternative would be loading it from: `http(s)://localhost:port/image.svg`.

**Comment by davidpelayo** [comment]
Either my previous or simply making it work from network by default when building in development mode.

Happy to provide a Pull Request with the changes I'm describing.

**Comment by AntonioRedondo** [comment]
Hi @davidpelayo,

If you create a pull request with the changes that would be amazing! Remember to update tests. I'll review the pull request once you open it. Ask me for any doubt you have.

Antonio 🙂

**Comment by AntonioRedondo** [comment]
This functionality is available on npm from version 2.2.6 😀 https://www.npmjs.com/package/html-webpack-inline-svg-plugin
