### ISSUE TITLE
Not converting to inline SVG

### ISSUE THREAD

**Issue by Rheisen** [theGC/html-webpack-inline-svg-plugin#3]
I'm trying to use this to convert some svg icons from images to inline svgs, but it doesn't appear to be catching them. After following the steps it still leaves the svg icons as images.

Example Usage (home.js):
```
import notebook from '../../assets/linea/_basic/_SVG/basic_notebook_pencil.svg';

class Example extends React.component {
  render() {
    return (
      <div>
        <img inline src={notebook} className={'icon icon-notebook'} />
      </div>
    )
  }
}
```

Webpack Config (webpack.common.js):

```
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const HtmlWebpackInlineSVGPlugin = require('html-webpack-inline-svg-plugin');

const HtmlWebpackPluginConfig = new HtmlWebpackPlugin({
  template: './app/client/base/index.html',
  filename: 'index.html',
  inject: 'body'
});

module.exports = {
...
plugins: [
    new CleanWebpackPlugin([path.resolve('./dist')], {root: process.cwd()}),
    HtmlWebpackPluginConfig,
    new HtmlWebpackInlineSVGPlugin()
  ]
}
```

I also use the file loader to catch svg images if that makes a difference.

**Comment by odiumediae** [comment]
Hi, @Rheisen, I'm currently having the same problem. Did you maybe happen to find a solution, yet?

**Comment by Rheisen** [comment]
@odiumediae Not yet unfortunately - I haven't given up though, I think it may have something to do with either the order in which things are getting bundled or the path to the file being changed by the file loader. If you figure anything out please let me know though.

**Comment by odiumediae** [comment]
@Rheisen Yeah, I think that's most likely the source of the problem, but I can't put my finger on it.

For me, the plugin inserts a hash-named new SVG file directly in the build folder and replaces the img's `src` attribute with it's path. That still works, but it's neither what I want nor what the plugin is supposed to do. The wird part is, that I get an error telling me it can't find the SVG file, even though the hashed file has its content.

There are a lot of clues as to what is going wrong, but it still can't find the actual problem. Anyway, maybe this helps you or others to some extent.

**Comment by theGC** [comment]
Hey, it'll likely be an issue with the method used to locate images on disk:

https://github.com/theGC/html-webpack-inline-svg-plugin/blob/19628536bcfd75fe06ca50f1a737153660e3abd5/index.js#L259

It's the one part I wasn't too happy with when I built the plugin as it doesn't account for the way Webpack resolves paths.

@Rheisen I'm assuming your issue is due to the use of a path relative to home.js

`../../assets/linea/_basic/_SVG/basic_notebook_pencil.svg`

When the plugin hits this it simply tries to resolve this path relative to your package.json file.

Have you tried using a path that is relative to package.json instead? It may be that this will fix it - however, it may also throw new errors if webpack can't find the file...

If you have a basic project I could pull then I could do some further testing.

**Comment by theGC** [comment]
Just looking at this again you'll definitely hit errors if you change this path as your importing it!

@Rheisen can you use:

`<img inline src="../../assets/linea/_basic/_SVG/basic_notebook_pencil.svg" className={'icon icon-notebook'} />`

If so can you make the above path relative to package.json and see if that works?

**Comment by theGC** [comment]
v1 supports the use of relative and aliased paths, I haven't tested it with React components but it should sort this issue.

I'll close for now but please let me know if this isn't the case.

**Comment by theGC** [comment]
looking at this again I seem to missed the point of what you were doing! my bad ...

Unless you are rendering the output of your React components to an html template **before** html-webpack-plugin is passed them then this plugin will have no effect on the components SVGs as it won't ever see them. Therefore perhaps this plugin is of use to you in an SSR environment but not for standard components.

Instead you need a webpack loader like: https://github.com/webpack-contrib/svg-inline-loader or: https://www.npmjs.com/package/svg-inline-react
