### ISSUE TITLE
Added NPM deploy to travis.yml

### ISSUE THREAD

**Issue by theGC** [theGC/html-webpack-inline-svg-plugin#30]
@AntonioRedondo 
Hey pal, just a note that I've added some config to the travis.yml which is auto-publishing to the NPM repo. Seems to be working after a bit of trial and error :)

**Comment by theGC** [comment]
the latest version: 2.2.6 was pushed to the master branch and published to npm correctly. The config looks for a new tag to be pushed to github, then on a successful build deploys it to pm. Therefore you'll need to `git push --tags` to trigger it.

**Comment by AntonioRedondo** [comment]
Oh cool. Blessing CI/CD features! ☜(ﾟヮﾟ☜)  Thanks 👍

**Comment by AntonioRedondo** [comment]
Hey @theGC, apart from the first option on [`svgo-config.js`](https://github.com/theGC/html-webpack-inline-svg-plugin/blob/master/svgo-config.js), is there any other option that, by default has to be different from the [SVGO defaults](https://github.com/svg/svgo#what-it-can-do)?

I'm thinking of removing any option from `svgo-config.js` that doesn't need to be different from SVGO defaults.

**Comment by theGC** [comment]
yeah this should be fine
