### ISSUE TITLE
can this create SVG definitions for re-use?

### ISSUE THREAD

**Issue by v3nt** [theGC/html-webpack-inline-svg-plugin#35]
hello - this looks great.

We are using the same SVG logos on 300 articles which means the same SVG code is inlined 300+ times. Is there a way the plugin can create a single definition of the inlined svg and then the 299 other uses are referenced to it? 

thanks.

**Comment by AntonioRedondo** [comment]
Hi @v3nt,

At the moment that feature isn't implemented in our plugin neither isn't scheduled to happen any time soon.

However what I can suggest is you inline your SVG in a CSS class then apply that class to your 300 `<div>` elements. This can be done with [PostCSS Assets](https://github.com/borodean/postcss-assets) and the function `inline()` in the CSS:
```css
div.myImage {
    background: inline('img/image.svg') no-repeat center / contain;
}
```

If you don't use PostCSS in your project problably there must be some other webpack plugin implementing same CSS inlining functionality.

**Comment by v3nt** [comment]
thanks - will try that.
