### ISSUE TITLE
Use alias

### ISSUE THREAD

**Issue by javipuche** [theGC/html-webpack-inline-svg-plugin#4]
webpack.config.js

```js
resolve: {
        alias: {
            assets: path.join(__dirname, './src/assets'),
        }
},
```
My html

```html
<img src="assets/svg/example.svg" inline> <!-- Not works -->
<img src="~assets/svg/example.svg" inline> <!-- Not works -->
```
Can't I use alias?

**Comment by theGC** [comment]
not at the moment - they'd need to be paths relative to your package.json file

I'm certainly not a fan of this - just when building the module it wasn't really an issue for me. However, the issues yourself and others have are now all related to this so I'd like to get it sorted. Any help (PR) would be much appreciated, otherwise I'll see if I can look into once work is a little quieter.

**Comment by theGC** [comment]
@javipuche just pushed v1 which supports the use of aliases and relative paths. #

**Comment by javipuche** [comment]
Thanks!!!!

**Comment by jameswragg** [comment]
I have an svg in `node_modules` I'm trying to inline but it's not working. Trying ../ as well as an alias, e.g. 

./webpack.config.js
```js
resolve: {
        alias: {
            nm: path.join(__dirname, './node_modules'),
        }
},
```

```html
<img inline src="../node_modules/packagename/dist/sprite.symbol.svg" /> <!-- Not working -->
<img inline src="~nm/packagename/dist/sprite.symbol.svg" /> <!-- Not working -->
```

I get this in my webpack build logs:
```js
undefined
processImages hit error
Error: ENOENT: no such file or directory, open '/Users/james.wragg/Repos/my-project/dist/~nm/packagename/dist/sprite.symbol.svg'
ENOENT: no such file or directory, open '/Users/james.wragg/Repos/my-project/dist/~nm/packagename/dist/sprite.symbol.svg'
```

Am I not able to step up out of the ./src dir anymore?

**Comment by theGC** [comment]
@jameswragg The plugin works with the files after their location has been resolved by Webpack, so it sounds like: `~nm` isn't being resolved.

If it was I'd expect the plugin to be looking for `sprite.symbol.svg` within your output directory. The fact it is throwing an error with `~nm` in it looks like Webpack hasn't parsed your html.

Do you have any loaders installed to allow Webpack to resolve the filenames within your template html? In the tests I'm using file-loader for the SVGs and html-loader to process the html. As this is a recent change (v1) I need to update the readme to explain it better.

**Comment by theGC** [comment]
@jameswragg I've updated the readme to better explain how you can use the plugin, I'd assume point 2 of Getting to your SVGs is the bit you need to look at: [getting-to-your-svgs](https://github.com/theGC/html-webpack-inline-svg-plugin#getting-to-your-svgs)
