### ISSUE TITLE
img tag removed but not replaced

### ISSUE THREAD

**Issue by WCByrne** [theGC/html-webpack-inline-svg-plugin#43]
I'm not sure what I'm missing in the readme but something isn't working. 

Given the options I thought `runPreEmit` sounded like the easiest way to reference the svg without needing to worry about where the output will end up, especially with Webpack dev server where I'm not even specifying an output path.

For some reason the `<img inline/>` tag is removed but not replaced with the svg.  If I change the path it crashes as expected so that doesn't seem like the problem. I don't think any loaders are at play.

Any ideas?
```
"html-webpack-inline-svg-plugin": "^2.3.0",
"html-webpack-plugin": "^5.3.1",
"webpack": "^5.35.1",
```

**Comment by AntonioRedondo** [comment]
`html-webpack-inline-svg-plugin` doesn't work with the webpack-dev-server unless you use the `runPreEmit` option: https://github.com/theGC/html-webpack-inline-svg-plugin/issues/19#issuecomment-548639977.

Are you using the webpack's [`output.publicPath`](https://webpack.js.org/configuration/output/#outputpublicpath) variable? If so this could be the reason of the issue.

**Comment by AntonioRedondo** [comment]
If you are using the `runPreEmit` option then make sure SVG files are referenced from the project ROOT and loaders are not involved. If you want them to work with the `webpack-dev-server` the SVG files must not be stored in the output directory.

Check the new documentation where all this is explained in a clearer way: https://github.com/theGC/html-webpack-inline-svg-plugin#paths-to-svg-files

I'm closing this issue. But if you still need help just leave a comment in this thread.
