### ISSUE TITLE
Can't get svg from my node_modules folder as I did in 0.2.2

### ISSUE THREAD

**Issue by httpete** [theGC/html-webpack-inline-svg-plugin#5]
Hi,

this plugin did exactly what I wanted in 0.2.2. It adds more html-loader configs and things now, was this done for a reason and if so will this old behavior break in the future?

**Comment by httpete** [comment]
<img inline src="node_modules/@company/components/theme/icons/symbol/svg/sprite.css.svg">
this worked fine, to get the svg from my node_modules folder.

**Comment by theGC** [comment]
@httpete @skayablars the update was brought on by our own requirements to better resolve relative file paths alongside a couple of issues that raised the question of resolving aliases for other users. Apologies for the breaking changes, I did try and detail what might happen in the readme but it's probably not that clear. I'll have another look at it.

You should still be able to use the module the way you did in v0.2.2 but need to be creating relative paths to your `node_modules` dir from the output location of your *html-webpack-plugin* templates, i.e.

If the output templates reside in: `<project-root>/dist/index.html`

and node_modules is at: `<project-root>/node_modules`

Then in your `index.html` change the src to:

`<img inline src="../node_modules/@company/components/theme/icons/symbol/svg/sprite.css.svg">`

This should work in situations where you are not parsing the templates with any loaders to resolve the SVG file paths. If it doesn't please ping me back here and I'll have a look into it.

**Comment by theGC** [comment]
As I haven't heard anymore I'll assume changing the file paths has worked. Let me know if not

**Comment by httpete** [comment]
This is broken. I tried all variants of ../../ to be relative. It injects "dist" into the path which I don't have. It worked SWEET before.

**Comment by theGC** [comment]
the plugin itself won't be injecting `dist` into your paths as it just reads them, is the issue instead with **html-loader** grabbing the svg from `node_modules` and putting it into your `dist` directory? If you remove the `inline` part, i.e

`<img src="node_modules/@company/components/theme/icons/symbol/svg/sprite.css.svg">`

can you check if the svg is moved into your `dist` directory and if so is the templates path correct?

**Comment by httpete** [comment]
I didn't use html-loader before, and the svg-inline-plugin just worked. I have to use another loader now? I would rather not but ok. (just documenting this here so others see)

**Comment by theGC** [comment]
sorry crossed wires I think, you shouldn't have to use any loaders - if you aren't then I'd expect the path of the svg to be exactly as you enter it. As you mentioned it having `dist` in it I'd assumed you had a loader parsing the template and resolving the svg path.

Does the path change when you don't add the **inline** attribute to your `img` tag?

**Comment by theGC** [comment]
to clarify I mean the svg's path within the output templates `img` tag

**Comment by httpete** [comment]
<img inline src="node_modules/@netapp/nwfjs_theme/icons/symbol/svg/sprite.css.svg">
 merrily works in 0.2.2.

if I upgrade, I get:

processImages hit error
Error: ENOENT: no such file or directory, open 'c:\Users\peters1\bench\project1\dist\node_modules\@netapp\nwfjs_theme\icons\symbol\svg\sprite.css.svg'

Note the "dist" injected there. I tried ../ no difference.

**Comment by theGC** [comment]
Without seeing your project it'll be tricky to diagnose what's going on here. However, I think it may be possible to add a flag to the plugin that will allow it to process svg's as it did in version < 1.0.

I'll ping back in a bit with an update

**Comment by httpete** [comment]
It seems that sass-loader uses ~ as a sort of "node_modules" alias, I tried that too. I'd love to be able to just be relative, or use the ~ as a pointer to my root level node_modules. Thanks @theGC

**Comment by theGC** [comment]
@httpete just pushed v1.1.1 which will allow you to pass an option to the plugin: `runPreEmit: true`

Doing so will revert the plugin back to working as it did prior to v1.0

I've detailed the set up in the readme, let me know if anything isn't clear or if you have any issues. I set up a bunch of tests and they're all passing so fingers crossed it'll just work as before for you.

**Comment by httpete** [comment]
I have it rigged to go, the second I can get it in my nexus I will try and give you feedback. Big tx!

**Comment by httpete** [comment]
I can confirm - `new HtmlWebpackInlineSVGPlugin({ runPreEmit: true }) ` works exactly as you say, the 0.2.2 way and works perfectly! Thank you @theGC
