### ISSUE TITLE
bug on htmlPluginData

### ISSUE THREAD

**Issue by wizardnet972** [theGC/html-webpack-inline-svg-plugin#7]
I found a bug.

 In `apply` function: `this.getUserConfig()`,  call without parameters, so `htmlPluginData` get undefined.

```
 getUserConfig (htmlPluginData) {

        this.userConfig =
            htmlPluginData &&
            htmlPluginData.plugin.options.svgoConfig &&
            _.isObject(htmlPluginData.plugin.options.svgoConfig) ?
            htmlPluginData.plugin.options.svgoConfig :
            {}

    }
```

**Comment by wizardnet972** [comment]
[PR #8](https://github.com/theGC/html-webpack-inline-svg-plugin/pull/8)

**Comment by theGC** [comment]
Hey, as the tests are failing on the PR i'll just add this to the a new release later today

**Comment by wizardnet972** [comment]
Thank you!
