### ISSUE TITLE
html-webpack-plugin-after-emit return promise

### ISSUE THREAD

**Issue by wizardnet972** [theGC/html-webpack-inline-svg-plugin#9]
error callback undefined.

In "html-webpack-plugin": "^3.0.4"

`html-webpack-plugin-after-emit` is return promise. not callback.

#webpack4

**Comment by wizardnet972** [comment]
@theGC If you can to fix it also in the next version so I can use it in my project I very much appreciate.
just check for callback null, say `callback && callback();` because `html-webpack-plugin-after-emit` is a promise in webpack4.

**Comment by theGC** [comment]
looks like it might need a bit more work to get the module compliant with the Webpack 4 API - will ping back when I have something

**Comment by wizardnet972** [comment]
Okay. If you need I would like to help :)

old webpack:
`    compiler.plugin('compilation', (compilation) => {`
in v4 is:
`    compiler.hooks.thisCompilation.tap('compilation', (compilation) => { `

:)

**Comment by theGC** [comment]
just pushed v1.2.2 and all seems to be passing. Have tested in both Webpack 3 & 4 and is working nicely.

Haven't updated to use `compiler.hooks.thisCompilation.tap` yet as that seems to be a breaking change which I must admit I'm not too sure how I want to handle as yet...

let me know if all working as expected
